import "@/assets/styles/globals.css"

import { ThemeProvider } from "@/components/ThemeProvider"
import { cn } from "@/lib/utils"
import { MainHeader } from "@/components/MainHeader"
import { MainHeaderItems } from "@/config/nav"
import { fontVariables } from '@/fonts'

export const metadata = {
  title: {
    default: "Pharmex",
    template: "%s | Pharmex",
  },
  description: 'Generated by create next app',
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "light" },
    { media: "(prefers-color-scheme: dark)", color: "dark" },
  ]
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head />
    <body
      className={cn(
        "min-h-screen bg-background font-sans antialiased", 
        ...fontVariables
      )}
    >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        {children}
      </ThemeProvider>
    </body>
  </html>
  )
}
