import "cal-sans"
import './globals.css'
import { Inter } from 'next/font/google'

const fontInter = Inter({ 
  subsets: ['latin'],
  variable: "--font-sans"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fontInter.className}>{children}</body>
    </html>
  )
}
